# The Site Configuration
theme: jekyll-theme-chirpy

# The language of the webpage
lang: pt-BR

# Timezone
timezone: America/Sao_Paulo

# --------------------------
# SEO / Site identity
# --------------------------

title: RPS Engenharia Insights
tagline: Energia, Data Centers e Infraestrutura

url: "https://insights.rpsengenharia.com"
baseurl: ""

# github:
#   username: rodolfoprezia

social:
  name: RPS Engenharia
  email: contato@rpsengenharia.com
  fediverse_handle: "http://rpsengenharia.com/"
  links:
    - https://www.linkedin.com/company/rpsengenharia/

# --------------------------
# Site verification
# --------------------------

webmaster_verifications:
  google: ""
  bing: ""
  alexa: ""
  yandex: ""
  baidu: ""
  facebook: ""

# --------------------------
# Analytics
# --------------------------

analytics:
  google:
    id: ""
  goatcounter:
    id: ""
  umami:
    id: ""
    domain: ""
  matomo:
    id: ""
    domain: ""
  cloudflare:
    id: ""
  fathom:
    id: ""

pageviews:
  provider: ""

# --------------------------
# Appearance
# --------------------------

theme_mode:

cdn:

avatar: /assets/img/rps-logo.png

social_preview_image:

toc: true

# --------------------------
# Comments
# --------------------------

comments:
  provider: ""

  disqus:
    shortname:

  utterances:
    repo:
    issue_term:

  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

# --------------------------
# Assets
# --------------------------

assets:
  self_host:
    enabled:
    env:

# --------------------------
# PWA
# --------------------------

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

paginate: 10

# --------------------------
# Core settings
# --------------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/

  - scope:
      path: _drafts
    values:
      comments: false

  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
